// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpxvuttxkytdelauzryx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpweHZ1dHR4a3l0ZGVsYXV6cnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTc4NDQsImV4cCI6MjA1OTU3Mzg0NH0.Tw9N4FwK0LhgOWlu1C7FLeaqylmmq2lku3QZ7O_KkKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);